# Generated by Django 6.0.4 on 2026-04-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
