# Generated by Django 6.0.4 on 2026-04-19 04:53

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
