# Generated by Django 6.0.2 on 2026-06-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0005_assurance_facture_taux_prise_en_charge_and_more'),
        ('patients', '0003_patient_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='facturation.assurance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero_assure',
            field=models.CharField(blank=True, default='', help_text="Numéro d'assuré / matricule (ex : numéro AMO).", max_length=50),
        ),
    ]
