# Generated by Django 6.0.2 on 2026-06-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_assurance_patient_numero_assure'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/'),
        ),
    ]
