# Generated by Django 6.0.4 on 2026-04-18 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('personnel', '0002_remove_infirmier_specialite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenmedical',
            name='resultat',
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='laborantin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.laborantin'),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.medecin'),
        ),
    ]
