# Generated by Django 6.0.4 on 2026-04-19 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_remove_examenmedical_resultat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='dossier_medical',
        ),
        migrations.AddField(
            model_name='consultation',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consultation.dossiermedical'),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='consultation.dossiermedical'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='consultation.dossiermedical'),
        ),
    ]
