# Generated by Django 6.0.4 on 2026-04-19 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_remove_consultation_dossier_medical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='consultation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation'),
            preserve_default=False,
        ),
    ]
