# Generated by Django 6.0.4 on 2026-04-19 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_traitement_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='consultation.dossiermedical'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traitement', to='consultation.dossiermedical'),
        ),
    ]
