# Generated by Django 6.0.5 on 2026-05-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_ordonnance_dossier_traitement_dossier'),
        ('patients', '0003_patient_date_creation'),
        ('personnel', '0003_receptionniste'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.TextField()),
                ('date_examen', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='consultation.dossiermedical')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.examenmedical')),
                ('laborantin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.laborantin')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
