# Generated by Django 6.0.5 on 2026-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_resultatexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenmedical',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
    ]
