# Generated by Django 6.0.5 on 2026-05-09 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_examenmedical_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultatexamen',
            name='dossier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='consultation.dossiermedical'),
        ),
    ]
