# Generated by Django 6.0.2 on 2026-06-02 18:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_alter_resultatexamen_dossier'),
        ('patients', '0003_patient_date_creation'),
        ('personnel', '0003_receptionniste'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='observation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resultatexamen',
            name='date_transmission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultatexamen',
            name='observations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resultatexamen',
            name='transmis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traitement',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='traitement',
            name='infirmier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements_assignes', to='personnel.infirmier'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='statut',
            field=models.CharField(choices=[('prescrit', 'Prescrit'), ('en_cours', 'En cours'), ('termine', 'Termine')], default='prescrit', max_length=20),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='consultation.dossiermedical'),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='consultation.examenmedical'),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='laborantin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.laborantin'),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.medecin'),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation'),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='duree',
            field=models.IntegerField(help_text='Duree en jours'),
        ),
        migrations.CreateModel(
            name='AdministrationTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.infirmier')),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='consultation.traitement')),
            ],
        ),
        migrations.CreateModel(
            name='AssistanceInfirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='consultation.dossiermedical')),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.infirmier')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='patients.patient')),
            ],
        ),
    ]
