# Generated by Django 6.0.2 on 2026-06-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_consultation_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenmedical',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='motif',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='examenmedical',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20),
        ),
    ]
