# Generated by Django 6.0.2 on 2026-06-18 18:46

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_examenmedical_date_examenmedical_motif_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultatexamen',
            options={'base_manager_name': 'objets_tous'},
        ),
        migrations.AlterModelManagers(
            name='resultatexamen',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('objets_tous', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='resultatexamen',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultatexamen',
            name='supprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultatexamen',
            name='supprime_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
