# Generated by Django 6.0.5 on 2026-06-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_alter_resultatexamen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='etat_clinique',
            field=models.CharField(choices=[('stable', 'Stable'), ('critique', 'Critique')], default='stable', max_length=20),
        ),
    ]
