# Generated by Django 6.0.4 on 2026-04-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarif',
            old_name='type_sevice',
            new_name='type_service',
        ),
    ]
