# Generated by Django 6.0.5 on 2026-06-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_add_description_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarif',
            options={'ordering': ['type_service', 'nom'], 'verbose_name': 'Tarif', 'verbose_name_plural': 'Tarifs'},
        ),
        migrations.AlterField(
            model_name='tarif',
            name='specialite',
            field=models.CharField(blank=True, help_text="Spécialité / Type d'examen / Type de chambre selon le service", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='type_service',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('examen', 'Examen médical'), ('hospitalisation', 'Hospitalisation (par nuit)')], max_length=20),
        ),
    ]
