# Generated by Django 6.0.2 on 2026-06-17 14:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0004_alter_tarif_options_alter_tarif_specialite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('taux_prise_en_charge', models.DecimalField(decimal_places=2, default=Decimal('70'), help_text="Pourcentage de la facture pris en charge par l'assurance (ex : 70 pour 70 %).", max_digits=5)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Assurance',
                'verbose_name_plural': 'Assurances',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='taux_prise_en_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taux de prise en charge appliqué à cette facture (%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='facture',
            name='assurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturation.assurance'),
        ),
    ]
