# Generated by Django 6.0.5 on 2026-08-12 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0017_backfill_dossier_proprietaire'),
        ('facturation', '0008_alter_paiement_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.examenmedical'),
        ),
        migrations.AddField(
            model_name='facture',
            name='ordonnance',
            field=models.ForeignKey(blank=True, help_text='Facture des médicaments dispensés pour cette ordonnance.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.ordonnance'),
        ),
    ]
