# Generated by Django 6.0.5 on 2026-08-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0009_facture_examen_facture_ordonnance'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_reclamation',
            field=models.DateField(blank=True, help_text="Date d'envoi de la demande de remboursement à l'assureur.", null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_remboursement',
            field=models.DateField(blank=True, help_text="Date à laquelle l'assureur a effectivement remboursé.", null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='statut_assurance',
            field=models.CharField(choices=[('a_reclamer', 'À réclamer'), ('reclame', 'Réclamé'), ('rembourse', 'Remboursé')], default='a_reclamer', help_text="Où en est le remboursement par l'assurance.", max_length=20),
        ),
    ]
