# Generated by Django 6.0.5 on 2026-08-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0017_backfill_dossier_proprietaire'),
        ('facturation', '0010_facture_date_reclamation_facture_date_remboursement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='rendez_vous',
            field=models.ForeignKey(blank=True, help_text='Consultation prépayée : facture établie dès la prise du rendez-vous.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.rendez_vous'),
        ),
    ]
