# Generated by Django 6.0.5 on 2026-06-29 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_journalaudit'),
        ('personnel', '0005_pharmacien'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='pharmacien',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil', to='personnel.pharmacien'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('medecin', 'Medecin'), ('laborantin', 'Laborantin'), ('infirmier', 'Infirmier'), ('receptionniste', 'Receptionniste'), ('pharmacien', 'Pharmacien')], max_length=30, unique=True),
        ),
    ]
