# Generated by Django 6.0.5 on 2026-06-17 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0010_examenmedical_date_examenmedical_motif_and_more'),
        ('patients', '0004_patient_assurance_patient_numero_assure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('dci', models.CharField(blank=True, default='', help_text='Dénomination commune internationale (principe actif), ex : Paracétamol.', max_length=150)),
                ('forme', models.CharField(blank=True, default='', help_text='Comprimé, sirop, injectable, pommade, gélule…', max_length=100)),
                ('dosage', models.CharField(blank=True, default='', help_text='Ex : 500 mg, 1 g, 100 mg/5 ml.', max_length=60)),
                ('categorie', models.CharField(blank=True, choices=[('antibiotique', 'Antibiotique'), ('antalgique', 'Antalgique / Antidouleur'), ('anti_inflammatoire', 'Anti-inflammatoire'), ('antipaludique', 'Antipaludique'), ('antipyretique', 'Antipyrétique'), ('cardiovasculaire', 'Cardiovasculaire'), ('digestif', 'Digestif / Gastro'), ('respiratoire', 'Respiratoire'), ('dermatologique', 'Dermatologique'), ('vitamine', 'Vitamines / Compléments'), ('autre', 'Autre')], default='', max_length=30)),
                ('unite', models.CharField(default='boîte', help_text='Unité de gestion du stock : boîte, comprimé, flacon…', max_length=30)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=10, help_text="Stock minimal : en dessous (ou égal), une alerte de réapprovisionnement s'affiche.")),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée (réapprovisionnement)'), ('sortie', 'Sortie (dispensation)')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('motif', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pharmacie.medicament')),
                ('ordonnance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensations', to='consultation.ordonnance')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
    ]
