# Generated by Django 6.0.5 on 2026-06-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0002_seed_medicaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix unitaire figé au moment du mouvement. Par défaut, celui du médicament.', max_digits=10),
        ),
    ]
