# Generated by Django 6.0.5 on 2026-06-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0003_mouvementstock_prix_unitaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='medicament',
            name='commun',
            field=models.BooleanField(default=False, help_text='Médicament de base, proposé à toutes les spécialités.'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='indication',
            field=models.TextField(blank=True, default='', help_text='À quoi sert ce médicament et dans quels cas le prescrire (aide à la prescription).'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='specialites',
            field=models.ManyToManyField(blank=True, help_text='Spécialités pour lesquelles ce médicament est proposé en priorité.', related_name='medicaments', to='pharmacie.specialite'),
        ),
    ]
