# Generated by Django 6.0.5 on 2026-06-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0005_seed_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='categorie',
            field=models.CharField(blank=True, choices=[('antibiotique', 'Antibiotique'), ('antalgique', 'Antalgique / Antidouleur'), ('anti_inflammatoire', 'Anti-inflammatoire'), ('antipaludique', 'Antipaludique'), ('antipyretique', 'Antipyrétique'), ('cardiovasculaire', 'Cardiovasculaire'), ('digestif', 'Digestif / Gastro'), ('respiratoire', 'Respiratoire'), ('dermatologique', 'Dermatologique'), ('vitamine', 'Vitamines / Compléments'), ('solute', 'Soluté / Perfusion'), ('antiseptique', 'Antiseptique / Désinfectant'), ('consommable', 'Consommable / Matériel médical'), ('autre', 'Autre')], default='', max_length=30),
        ),
    ]
