# Generated by Django 6.0.5 on 2026-06-26 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0006_seed_assurances'),
        ('pharmacie', '0007_seed_consommables'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='facture',
            field=models.ForeignKey(blank=True, help_text='Facture sur laquelle ce médicament dispensé est porté (le cas échéant).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='facturation.facture'),
        ),
    ]
