# Generated by Django 6.0.5 on 2026-05-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_remove_infirmier_specialite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionniste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('role', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
