# Generated by Django 6.0.5 on 2026-06-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_receptionniste'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadministratif',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personnel/photos/'),
        ),
        migrations.AddField(
            model_name='infirmier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personnel/photos/'),
        ),
        migrations.AddField(
            model_name='laborantin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personnel/photos/'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personnel/photos/'),
        ),
        migrations.AddField(
            model_name='receptionniste',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personnel/photos/'),
        ),
    ]
