# Generated by Django 6.0.5 on 2026-06-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_agentadministratif_photo_infirmier_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('role', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/photos/')),
                ('service', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
